// Prueba de aceptación del CRM desplegado, con un navegador real (Playwright + Chromium). Crea datos de ejemplo y verifica el flujo comercial.
const { chromium } = require('/root/pw/node_modules/playwright-core')
const fs = require('fs')
const URL = process.env.CRM_URL
const SHOTS = '/root/crm-shots'
fs.mkdirSync(SHOTS, { recursive: true })
let fallos = 0
const ok = (c, m, x) => { if (!c) fallos++; console.log(`${c ? '  ok  ' : ' FALLA'} ${m}${!c && x !== undefined ? ' → ' + String(x).slice(0, 200) : ''}`) }
const texto = async (page) => (await page.locator('body').innerText()).replace(/\s+/g, ' ')

;(async () => {
  const exe = fs.readdirSync('/root/.cache/ms-playwright').filter(d => d.startsWith('chromium-')).sort().pop()
  const browser = await chromium.launch({ executablePath: `/root/.cache/ms-playwright/${exe}/chrome-linux64/chrome`, args: ['--no-sandbox'] })
  const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 } })).newPage()
  const errores = []
  page.on('pageerror', e => errores.push(String(e)))
  page.on('console', m => { if (m.type() === 'error') errores.push(m.text()) })
  const suf = Date.now().toString().slice(-5)

  console.log('— Empresas')
  await page.goto(URL + '/empresas'); await page.waitForLoadState('networkidle')
  await page.fill('input[name=nit]', 'abc'); await page.fill('input[name=razonSocial]', 'Empresa con NIT malo')
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(600)
  let t = await texto(page)
  ok(!t.includes('Empresa con NIT malo') || /NIT|inválid|invalid/i.test(t), 'un NIT inválido no se guarda en silencio', t.slice(0, 160))
  await page.goto(URL + '/empresas'); await page.waitForLoadState('networkidle')
  await page.fill('input[name=nit]', `900${suf}-1`); await page.fill('input[name=razonSocial]', `Ferretería El Tornillo ${suf} SAS`)
  await page.fill('input[name=ciudad]', 'Pereira'); await page.fill('input[name=sector]', 'Ferretería'); await page.fill('input[name=vendedor]', 'ana@andina.example')
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(800)
  t = await texto(page)
  ok(t.includes(`Ferretería El Tornillo ${suf} SAS`), 'la empresa creada aparece en el listado', t.slice(0, 200))
  await page.screenshot({ path: `${SHOTS}/1-empresas.png` })
  // NIT duplicado
  await page.fill('input[name=nit]', `900${suf}-1`); await page.fill('input[name=razonSocial]', 'Duplicada')
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(800)
  t = await texto(page)
  ok(!t.includes('Duplicada') || /ya existe|duplic|único|unique/i.test(t), 'un NIT repetido no crea una segunda empresa', t.slice(0, 200))

  console.log('— Contactos')
  await page.goto(URL + '/empresas'); await page.waitForLoadState('networkidle')
  await page.locator('a[href^="/empresas/"]').filter({ hasText: `900${suf}-1` }).first().click()
  await page.waitForLoadState('networkidle'); await page.waitForTimeout(500)
  ok(/\/empresas\/[^/]+$/.test(page.url()), 'el detalle de la empresa abre', page.url())
  const campos = await page.locator('input[name]').evaluateAll(els => els.map(e => e.getAttribute('name')))
  ok(campos.includes('nombre') && campos.includes('email'), 'el detalle tiene el formulario de contacto', campos.join(','))
  await page.fill('input[name=nombre]', 'Luis Mejía'); await page.fill('input[name=email]', 'correo-invalido')
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(800)
  t = await texto(page)
  ok(!t.includes('Luis Mejía') || /email|correo/i.test(t), 'un email inválido se rechaza', t.slice(0, 200))
  await page.fill('input[name=nombre]', 'Luis Mejía'); await page.fill('input[name=email]', 'luis@tornillo.example')
  if (campos.includes('cargo')) await page.fill('input[name=cargo]', 'Compras')
  if (campos.includes('telefono')) await page.fill('input[name=telefono]', '3101234567')
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(800)
  t = await texto(page)
  ok(t.includes('Luis Mejía') && t.includes('luis@tornillo.example'), 'el contacto creado aparece en el detalle', t.slice(0, 200))
  await page.screenshot({ path: `${SHOTS}/2-detalle-empresa.png` })

  console.log('— Oportunidades')
  await page.goto(URL + '/oportunidades'); await page.waitForLoadState('networkidle')
  await page.fill('input[name=titulo]', `Pedido anual de tornillería ${suf}`)
  const opciones = await page.locator('select[name=empresaId] option').allInnerTexts()
  const idx = opciones.findIndex(o => o.includes(`Tornillo ${suf}`))
  ok(idx >= 0, 'la empresa nueva está en el selector de oportunidades', opciones.join('|').slice(0, 160))
  await page.selectOption('select[name=empresaId]', { index: idx })
  await page.fill('input[name=valor]', '5000000'); await page.fill('input[name=vendedor]', 'ana@andina.example')
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(800)
  t = await texto(page)
  ok(t.includes(`Pedido anual de tornillería ${suf}`), 'la oportunidad creada aparece en el tablero', t.slice(0, 200))
  ok(/5\.000\.000|5,000,000/.test(t), 'el valor se muestra en pesos con separador', t.match(/\$[^ ]*/g)?.slice(0, 3).join(' '))
  const tarjeta = page.locator('div, li, article').filter({ hasText: `Pedido anual de tornillería ${suf}` }).filter({ has: page.getByRole('button', { name: /Avanzar/i }) }).last()
  await tarjeta.getByRole('button', { name: /Avanzar/i }).click(); await page.waitForLoadState('networkidle'); await page.waitForTimeout(900)
  await tarjeta.getByRole('button', { name: /Avanzar/i }).click().catch(() => {}); await page.waitForLoadState('networkidle'); await page.waitForTimeout(900)
  await page.screenshot({ path: `${SHOTS}/3-oportunidades.png`, fullPage: true })
  // en qué columna quedó: la etapa debe ser COTIZADO (dos avances desde PROSPECTO)
  const col = await page.evaluate((titulo) => {
    const nodos = [...document.querySelectorAll('*')].filter(n => n.children.length && n.textContent && n.textContent.includes(titulo))
    const h = nodos.map(n => n.closest('section, div'))?.filter(Boolean)
    return document.body.innerText.split('\n').join(' | ').slice(0, 1200)
  }, `Pedido anual de tornillería ${suf}`)
  ok(/COTIZADO|Cotizado/.test(col), 'tras dos avances la oportunidad está en la etapa Cotizado', col.slice(0, 300))

  console.log('— Actividades')
  await page.goto(URL + '/actividades'); await page.waitForLoadState('networkidle')
  const ayer = new Date(Date.now() - 36 * 3600e3); const pad = n => String(n).padStart(2, '0')
  const dt = `${ayer.getFullYear()}-${pad(ayer.getMonth() + 1)}-${pad(ayer.getDate())}T09:00`
  await page.selectOption('select[name=tipo]', { index: 1 }); await page.fill('input[name=descripcion]', `Llamar para el seguimiento de la cotización ${suf}`)
  await page.fill('input[name=fecha]', dt)
  await page.click('button[type=submit]'); await page.waitForLoadState('networkidle'); await page.waitForTimeout(900)
  t = await texto(page)
  ok(t.includes(`seguimiento de la cotización ${suf}`), 'la actividad creada aparece', t.slice(0, 200))
  ok(/Vencida/.test(t), 'una actividad con fecha pasada se marca como vencida', t.slice(0, 200))
  await page.screenshot({ path: `${SHOTS}/4-actividades-vencida.png`, fullPage: true })

  console.log('— KPIs')
  await page.goto(URL + '/'); await page.waitForLoadState('networkidle')
  t = await texto(page)
  ok(/Oportunidades abiertas\s*[1-9]/.test(t), 'el tablero cuenta la oportunidad abierta', t.slice(0, 260))
  ok(/Actividades vencidas\s*[1-9]/.test(t), 'el tablero cuenta la actividad vencida', t.slice(0, 260))
  ok(/5\.000\.000/.test(t) || /5,000,000/.test(t), 'el valor del pipeline refleja la oportunidad', t.slice(0, 260))
  await page.screenshot({ path: `${SHOTS}/5-kpis.png`, fullPage: true })
  await page.setViewportSize({ width: 390, height: 800 }); await page.reload(); await page.waitForLoadState('networkidle')
  await page.screenshot({ path: `${SHOTS}/6-kpis-movil.png`, fullPage: true })
  const desborde = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 4)
  ok(!desborde, 'en un celular no hay desborde horizontal', 'scrollWidth > viewport')

  ok(errores.length === 0, 'sin errores de consola ni de página', errores.slice(0, 3).join(' || '))
  await browser.close()
  console.log(fallos === 0 ? '\nTODO OK' : `\n${fallos} FALLA(S)`)
})().catch(e => { console.error('EXCEPCIÓN', e.message); process.exit(1) })
